### ISSUE TITLE
Do you want to animate anything with those svg liners?

### ISSUE THREAD

**Issue by artivilla** [jereford/willingtoadmit#1]
This svg tracker has become super simple and there are tons of libraries on this now:
https://github.com/ConnorAtherton/walkway. I'm particularly looking at walker.js: https://connoratherton.com/walkway.

Let me know if we can incorporate something subtle here or in progressive punctuation.

Also, can you add a profile picture to your account? :+1:

**Comment by jereford** [comment]
Ooh I like this! Not sure if it has a place in the WillingToAdmit project but potentially the punctuation?

**Comment by artivilla** [comment]
Nice, oops I'm such an idiot. I thought my issue needed to be pushed :/ Haha.
